#!/bin/bash
DIR=$PWD
DELAY=false
PRINTONLY=false
DELAYTIME=1
PATTERN=""
WD="wd"
PARTITION="allgpu"
EXCLUDEWEAKNODES=false
STRONGNODES=false
OVERSUBSCRIBE=false
NODELIST=""
SLURMARGS=""
cd $DIR


usage() {
    echo "Usage: $0 [-a SLURMARGS] [-d DIR ... defaults to PWD] [-f PARTITION ... defaults to allgpu] [-h help] [-n nodelist] [-o oversubscribe] [-p PATTERN] [-s strong] [-t DELAYTIME sleep before next submit in seconds, disabled by default] [-w workingDir default to wd] [-x exclude weak]" 1>&2
    exit 1
}

while getopts "a:d:f:hn:op:st:w:x" o; do
    case "${o}" in
        a)
            SLURMARGS=${OPTARG}
            ;;
        d)
            DIR=${OPTARG}
            ;;
        f)
            PARTITION=${OPTARG}
            ;;
        h)
            usage
            exit 0
            ;;
		n)
	    	NODELIST=${OPTARG}
	    	;;
        o)
            OVERSUBSCRIBE=true
            ;;
        p)
            PATTERN=${OPTARG}
            ;;
        s)
            STRONGNODES=true
            ;;
        t)
            DELAY=true
            DELAYTIME=${OPTARG}
            ;;
        w)
            WD=${OPTARG}
            ;;
        x)
            EXCLUDEWEAKNODES=true
            ;;
        *)
            usage
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))


SCRIPT=$1
echo "Executing script ${SCRIPT} in ${DIR}"
ARG=""
SCRIPTNAME=$(basename $SCRIPT)
SCRIPTNAME=${SCRIPTNAME%.*}


CMD="find ${WD} -mindepth 1 -maxdepth 1 \( -type d -o -type l \)" 
if [ -n "$PATTERN" ]; then
	CMD="$CMD -iregex '.*$PATTERN.*'"
fi

if [ -f sbatch/${SCRIPT} ]; then
	SCRIPT=sbatch/${SCRIPT}
else
	if [ -f ${SCRIPT} ]; then
		SCRIPT=${SCRIPT}
	else
		echo "Script sbatch/${SCRIPT} or ${SCRIPT} does not exist"
		exit 1
	fi
fi




if [ $EXCLUDEWEAKNODES = true ]; then
	WEAKNODES=$(listMaxwellNodes -p ${PARTITION} -w)
	ARG="$ARG --exclude=$WEAKNODES"
fi

# Set --nodelist either explicitly or by using --strong by querying the list of strong nodes
if [ -n "$NODELIST" ] && [ $STRONGNODES = true ]; then
	echo "You cannot use --nodelist and --strong at the same time"
	exit 1
fi
if [ -n "$NODELIST" ]; then
	ARG="$ARG --nodelist=$NODELIST"
fi
if [ $STRONGNODES = true ]; then
	STRONGNODES=$(listMaxwellNodes -p ${PARTITION} -s)
	ARG="$ARG --nodelist=$STRONGNODES"
fi

if [[ $OVERSUBSCRIBE = true ]]; then
	ARG="$ARG --oversubscribe"
fi
if [[ $PARTITION != "allgpu" ]]; then
	ARG="$ARG --partition=${PARTITION}"
fi

for WDD in $( eval $CMD ); do
	JOBNAME="${SCRIPTNAME}_$WDD"
	if [ $DELAY = true ]; then
		sleep $DELAYTIME
	fi
    CMD="sbatch ${ARG} --job-name=${JOBNAME} ${SCRIPT} $WDD"
    if [ -n "$SLURMARGS" ]; then
        CMD="$CMD $SLURMARGS"
    fi
    echo $CMD
    if [ $PRINTONLY = false ]; then
        eval $CMD
    fi
done

#It is possible to create file with individual files
#find wd -mindepth 1 -maxdepth 1 -type d | awk '$0="sbatch sbatch/06detectRotationCenter_sinogramConsistency_additional.sbatch "$0'>>sbatch/06detectRotationCenter_store.exe
