#!/bin/bash
DIR=$PWD
DELAY=false
PRINTONLY=false
DELAYTIME=1
PATTERN=""
cd $DIR

usage() { echo "Usage: $0 [-t DELAYTIME sleep before next submit in seconds, disabled by default] [-d DIR ... defaults to PWD] [-p pattern]" 1>&2; exit 1; }

while getopts "t:d:p:h" o; do
	case "${o}" in
		t)
			DELAY=true
			DELAYTIME=${OPTARG}
			;;
		d)
			DIR=${OPTARG}
			;;
		p)
			PATTERN=${OPTARG}
			;;
		h)
			usage
			exit 0
			;;
		*)
			usage
			exit 0
			;;
		esac
done
shift $((OPTIND-1))

SCRIPT=$1
echo "Executing script ${SCRIPT} in ${DIR}"



CMD="find wd -mindepth 1 -maxdepth 1 -type d" 
if [ -n "$PATTERN" ]; then
	CMD="$CMD -iregex '.*$PATTERN.*'"
fi


for x in $( eval $CMD ); do
	if [ $DELAY = true ]; then
		sleep $DELAYTIME
	fi
	echo sbatch sbatch/${SCRIPT} $x
	if [ $PRINTONLY = false ]; then
		sbatch sbatch/${SCRIPT} $x
	fi
done

#It is possible to create file with individual files
#find wd -mindepth 1 -maxdepth 1 -type d | awk '$0="sbatch sbatch/06detectRotationCenter_sinogramConsistency_additional.sbatch "$0'>>sbatch/06detectRotationCenter_store.exe
